UNAME_S := $(shell uname -s)

# `uname -s` is IRIX64 on a 64-bit kernel and plain IRIX on a 32-bit one, so an
# Indy reports IRIX where an Octane reports IRIX64. Matching only IRIX64 sent
# every 32-bit machine down the Linux branch, where it picked up -D_GNU_SOURCE
# and a dynamic OpenSSL and failed on the first header.
IS_IRIX := $(filter IRIX IRIX64,$(UNAME_S))

# Cross-compiling for IRIX from a Linux host. uname reports the host, so the
# toolchain announces itself instead: IRIX_SYSROOT is set by the image that
# carries clang, mogrix's IRIX linker and a cross-built OpenSSL.
CROSS_IRIX := $(if $(IRIX_SYSROOT),1,)

BUILD   := build

# src/serve/ is host-only. Excluded here rather than behind an #if, which would
# leave MIPSPro an empty translation unit; ISO C forbids that.
ifneq ($(IS_IRIX)$(CROSS_IRIX),)
PLATFORM_SRCS :=
else
PLATFORM_SRCS := $(wildcard src/serve/*.c)
endif

# Everything except main.c, so each test binary can supply its own entry point.
LIB_SRCS  := $(wildcard src/compat/*.c src/net/*.c src/crypto/*.c \
	src/json/*.c src/proto/*.c src/exec/*.c src/expr/*.c \
	src/sandbox/*.c) $(PLATFORM_SRCS)
SRCS      := $(LIB_SRCS) src/main.c
LIB_OBJS  := $(LIB_SRCS:%.c=$(BUILD)/%.o)
OBJS      := $(SRCS:%.c=$(BUILD)/%.o)
TEST_SRCS := $(wildcard test/*.c)
TEST_BINS := $(TEST_SRCS:test/%.c=$(BUILD)/%)

WARNS   := -Wall -Wextra -Wno-unused-parameter

ifneq ($(CROSS_IRIX),)
# Cross build. Produces the same n32 MIPS-III binary as the IRIX branch.
# GCC dropped mips-sgi-irix6.5 in the 4.8 era, so clang is the only current
# compiler for the target; irix-cc wraps it with the ABI flags and the header
# shims that stand in for MIPSPro builtins.
MOGRIX  ?= /opt/mogrix
CC      := $(MOGRIX)/cross/bin/irix-cc
# No -mips3 or -mabi=n32 here: irix-cc sets the ABI itself, and passing the GCC
# spellings on top makes clang reject the command line.
CFLAGS  := -std=c99 -O2 $(WARNS) -I$(IRIX_OPENSSL)/include -Isrc
# OpenSSL is cross-built with this same toolchain rather than taken from
# SGUG-RSE. LLD cannot read SGUG's archives at all: GNU as emits STB_LOCAL
# symbols past sh_info and LLD rejects the object outright.
#
# -lpthread, not -pthread. The IRIX branch's rule is about GCC's driver spec;
# here irix-cc hands the link to LLD directly, which has no spec to expand and
# silently drops -pthread.
LIBS    := $(IRIX_OPENSSL)/lib/libssl.a $(IRIX_OPENSSL)/lib/libcrypto.a \
           -lpthread -lm
LDFLAGS :=
else ifneq ($(IS_IRIX),)
SGUG    := /usr/sgug
CC      := $(SGUG)/bin/gcc
# -Isrc must precede the SGUG include dir. SGUG ships JsonCpp at
# /usr/sgug/include/json/json.h, which collides with our own json/json.h; with
# the order reversed, MIPSPro pulls in the C++ header and dies on <cstddef>.
# -mips3 is the portability floor, not a default worth inheriting. MIPS III is
# R4000 and later, which is every CPU that can run IRIX 6.5; a mips-4 binary
# would silently exclude the R4400 and R5000 machines this project exists for.
# The release workflow asserts the ISA of the shipped binary against this.
CFLAGS  := -std=c99 -O2 $(WARNS) -mabi=n32 -mabicalls -mips3 \
           -D_SGI_SOURCE -D_SGI_MP_SOURCE -D_SGI_REENTRANT_FUNCTIONS \
           -Isrc -I$(SGUG)/include
# Static OpenSSL keeps the binary self-contained on machines without SGUG-RSE.
# -lz is required: SGUG builds OpenSSL with zlib. MIPSPro's ld32 dies with an
# internal error on these archives, so GNU ld does all linking.
LIBS    := $(SGUG)/lib32/libssl.a $(SGUG)/lib32/libcrypto.a $(SGUG)/lib32/libz.a -pthread
LDFLAGS := -Wl,-rpath,/usr/lib32
else
# Development and unit-test host. IRIX ships OpenSSL 1.1.1d and that is the API
# the sources target; pinning the compatibility level here keeps one code path
# instead of forking it for whatever version the dev box happens to have.
CC      ?= gcc
CFLAGS  := -std=c99 -O2 -g $(WARNS) -D_GNU_SOURCE -Isrc \
           -DOPENSSL_API_COMPAT=0x10100000L -DOPENSSL_SUPPRESS_DEPRECATED
LIBS    := -lssl -lcrypto -pthread
LDFLAGS :=
endif

# Header dependencies, generated by the compiler.
#
# Without these a header change recompiles nothing, and objects built against
# different layouts of the same struct get linked together. That produced a
# job whose step count read as zero while the parser had found them correctly,
# which is a miserable thing to debug.
DEPS := $(OBJS:.o=.d) $(TEST_SRCS:test/%.c=$(BUILD)/%.d)
CFLAGS += -MMD -MP

.PHONY: all check tests test test-run clean grammar

all: $(BUILD)/runner

# Manual on purpose: the generated parser is committed so no ordinary build
# needs bison, and an automatic rule would quietly use stale tables.
grammar:
	cd src/expr && bison -d -o grammar.tab.c grammar.y

$(BUILD)/runner: $(OBJS)
	@mkdir -p $(@D)
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

$(BUILD)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -c -o $@ $<

# Portability gate. MIPSPro is compile-only; it rejects GNU C extensions, so a
# clean run here means the source stays buildable with the stock SGI compiler.
# The %z grep is not style policing: IRIX libc printf does not consume the
# argument, which corrupts varargs parsing and segfaults on a following %s.
check:
	@! grep -rn '%[-+ #0-9.*]*z[udixX]' src/ test/ \
	  || { echo "error: %z format specifier segfaults on IRIX, see CLAUDE.md"; exit 1; }
	@echo "ok: no %z format specifiers"
ifneq ($(IS_IRIX),)
	@mkdir -p $(BUILD)/mipspro
	@for f in $(SRCS); do \
	  echo "c99 $$f"; \
	  PATH=/usr/bin:/bin /usr/bin/c99 -n32 -O2 -c \
	    -o $(BUILD)/mipspro/check.o \
	    -D_SGI_SOURCE -D_SGI_MP_SOURCE -D_SGI_REENTRANT_FUNCTIONS \
	    -Isrc -I/usr/sgug/include $$f || exit 1; \
	done
	@rm -rf $(BUILD)/mipspro
	@echo "ok: MIPSPro c99 clean"
else
	@echo "skip: MIPSPro check needs IRIX"
endif

# Build the test binaries without running them, for a cross build whose output
# executes on another machine.
tests: $(TEST_BINS)

# A recipe, not `test: tests test-run`. Prerequisites of a phony target are
# unordered, so under -j the run starts before the binaries exist and fails
# claiming they were never built.
test: tests
	@$(MAKE) --no-print-directory test-run

# Runs test binaries that already exist, so a machine that cannot build them can
# still be the one that executes them. The release cross-compiles on Linux and
# runs this on a real arm64 and a real SGI.
test-run:
	@for t in $(TEST_BINS); do \
	  test -x $$t || { echo "missing $$t; build it first"; exit 1; }; \
	  echo "run $$t"; $$t || exit 1; \
	done

$(BUILD)/%: test/%.c $(LIB_OBJS)
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(LIB_OBJS) $(LIBS)

clean:
	rm -rf $(BUILD)

-include $(DEPS)
