"""
Derive the throwaway e2e workflow from release.yml.

release.yml only fires on a tag, so nothing in it can be exercised on a branch.
This lifts every job except publish, takes the version from src/version.h
instead of the tag, and adds a verify job that checks the tarballs the way
publish would.

Delete .github/workflows/scratch-e2e.yml before merging.
"""
import pathlib
import yaml

RELEASE = pathlib.Path('.github/workflows/release.yml')
SCRATCH = pathlib.Path('.github/workflows/scratch-e2e.yml')

VERSION_FROM_HEADER = (
    "ver=$(sed -n 's/^#define[[:space:]]*SGUG_PROJECT_VERSION"
    "[[:space:]]*\"\\(.*\\)\".*/\\1/p' src/version.h)"
)

HEADER = """\
# Temporary. Runs every job in release.yml except publish, which needs a tag.
# The version comes from src/version.h; the job bodies are lifted unchanged.
# Generated by contrib/cross/mkscratch.py. Delete before merging.
"""


def block_scalars(dumper, data):
    """Keep shell bodies readable. Without this every run: becomes one escaped
    line, which is unreviewable and the whole point of the file is review."""
    if '\n' in data:
        return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
    return dumper.represent_scalar('tag:yaml.org,2002:str', data)


def retarget(job, needs=None):
    if needs:
        job['needs'] = needs
    else:
        job.pop('needs', None)
    for step in job.get('steps', []):
        if 'run' in step:
            step['run'] = step['run'].replace(
                'ver="${GITHUB_REF_NAME#v}"', VERSION_FROM_HEADER)
    return job


def main():
    jobs = yaml.safe_load(RELEASE.read_text())['jobs']

    out = {
        'build-irix': retarget(jobs['build-irix']),
        'test-irix': retarget(jobs['test-irix'], 'build-irix'),
        'package-irix': retarget(jobs['package-irix'], 'test-irix'),
        'build-linux': retarget(jobs['build-linux']),
        'test-linux': retarget(jobs['test-linux'], 'build-linux'),
        'package-linux': retarget(jobs['package-linux'], 'test-linux'),
    }

    verify = [s for s in jobs['publish']['steps']
              if s.get('name', '').startswith('Verify')]
    out['verify'] = {
        'needs': ['package-irix', 'package-linux'],
        'runs-on': 'ubuntu-latest',
        'steps': [
            {'uses': 'actions/checkout@v4'},
            {'uses': 'actions/download-artifact@v4',
             'with': {'pattern': '*-dist*', 'path': 'dl'}},
        ] + verify,
    }

    # `on` is a YAML 1.1 boolean, so it round-trips as `true:` unless quoted.
    doc = {
        'name': 'scratch e2e',
        'on': {'push': {'branches': ['release/cross-and-test-on-target']}},
        'permissions': {'contents': 'read', 'packages': 'read'},
        'jobs': out,
    }

    dumper = yaml.SafeDumper
    dumper.add_representer(str, block_scalars)
    body = yaml.dump(doc, Dumper=dumper, sort_keys=False, width=100,
                     default_flow_style=False)
    SCRATCH.write_text(HEADER + body.replace('\non:\n', '\n"on":\n', 1))


if __name__ == '__main__':
    main()
